server:
  port: 8080
spring:
  profiles:
    active: git,docker
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: file:///config-repository
          default-label: master
          search-paths: .
